<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.1</Version>
    <PackageProjectUrl>https://github.com/WasaBeeXD/Sampleplugin</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Copyright>Copyright © 2026</Copyright>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

<PropertyGroup>
  <!-- Verhindert die Anzeige von Versionskonflikt-Warnungen -->
  <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
  <NoWarn>$(NoWarn);MSB3277</NoWarn>
</PropertyGroup>

<PropertyGroup>
    <!-- Das verhindert die Fehlermeldung auf GitHub -->
    <DalamudLibPath Condition="'$(GITHUB_ACTIONS)' == 'true'">$(SolutionDir)references\</DalamudLibPath>
</PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\goat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>