name: Release
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Build Plugin
        # Wir bauen direkt die .csproj, NICHT die .sln
        # Wir setzen den Pfad auf '.', damit er denkt, die Libs liegen im aktuellen Ordner
        run: dotnet build SamplePlugin.csproj -c Release --output ./publish -p:DalamudLibPath=. -p:Deterministic=true

      - name: Create Zip
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath ./latest.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
