name: Release
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Build & Release
        uses: goatcorp/Action-DalamudRelease@v1
        with:
          project-name: SamplePlugin
          release-variant: main
